image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm ci && cd packages/e2e && npx playwright install chromium && cd ../../ && npm test

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
